[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Noah West", email = "westnoahb@gmail.com"},
]
dependencies = [
    "kivy>=2.1.0",
    "autopep8>=2.0.1",
]
requires-python = ">=3.10"
license = {text = "MIT"}
